---
title: "1a. Overview"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 1
    number_sections: true
    self_contained: yes
vignette: >
  %\VignetteIndexEntry{1a. Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, eval = TRUE, echo = FALSE, message=FALSE}
# global option chunks
knitr::opts_chunk$set(
  fig.width = 7,
  fig.height = 10,
  dpi = 70,
  comment = "",
  out.width = "80%",
  fig.align = "center",
  message = TRUE,
  warning = TRUE
)

#options(width = 100, max.print = 100)
```

## A description of each of the 'gibbonNetR' functions
'gibbonNetR' contains functions for the automated detection and classification of acoustic signals. A brief summary of the functions is shown below.

```{r, echo=FALSE, results="asis"}
cat("| File Name                                  | Description                                      |\n")
cat("|-------------------------------------------|--------------------------------------------------|\n")
cat("| deploy_CNN_binary.R                      | Deploys a trained binary CNN model over a directory of sound files               |\n")
cat("| deploy_CNN_multi.R                       | Deploys a trained multi-class CNN model over a directory of sound files          |\n")
cat("| evaluate_trainedmodel_performance_multi.R | Evaluates performance of a multi-class model on a test dataset     |\n")
cat("| evaluate_trainedmodel_performance.R      | Evaluates performance of a binary model on a test dataset          |\n")
cat("| extract_embeddings.R                     | Extracts feature embeddings from trained models   |\n")
cat("| get_best_performance.R                   | A function that benchmarks multiple trained models    |\n")
cat("| spectrogram_images.R                     | Generates and processes spectrogram images       |\n")
cat("| train_CNN_binary.R                       | Trains a binary classification CNN model        |\n")
cat("| train_CNN_multi.R                        | Trains a multi-class classification CNN model   |\n")
```

## A flowchart overview of the 'gibbonNetR' workflow
Below is a sample workflow using the 'gibbonNetR' package. 
```{r, eval = TRUE, echo = FALSE, message=FALSE}
if (!requireNamespace("DiagrammeR", quietly = TRUE)) {
  install.packages("DiagrammeR")
}
# Install required package if not installed
library(DiagrammeR)

flowchart <- "
digraph G {
  graph [layout = dot, rankdir = TB]

  # Nodes: Scripts as rectangles, key decision points as diamonds
  spectrogram [label = 'Generate Spectrograms\\n(spectrogram_images.R)', shape = rectangle, style = filled, fillcolor = lightblue]
  prepare_data [label = 'Prepare Sound Data', shape = diamond, style = filled, fillcolor = white]
  
  train_model [label = 'Train Model', shape = diamond, style = filled, fillcolor = white]
  train_binary [label = 'Train Binary CNN\\n(train_CNN_binary.R)', shape = rectangle, style = filled, fillcolor = green]
  train_multi [label = 'Train Multi CNN\\n(train_CNN_multi.R)', shape = rectangle, style = filled, fillcolor = green]

  eval_model [label = 'Benchmark Performance of Different Models', shape = diamond, style = filled, fillcolor = white]
  best_performance [label = 'Get Best Performance\\n(get_best_performance.R)', shape = rectangle, style = filled, fillcolor = pink]
  
  eval_test_set [label = 'Evaluate Performance on Test Set', shape = diamond, style = filled, fillcolor = white]
  eval_binary [label = 'Evaluate Binary CNN\\n(evaluate_trainedmodel_performance.R)', shape = rectangle, style = filled, fillcolor = pink]
  eval_multi [label = 'Evaluate Multi CNN\\n(evaluate_trainedmodel_performance_multi.R)', shape = rectangle, style = filled, fillcolor = pink]

  deploy_model [label = 'Deploy Model', shape = diamond, style = filled, fillcolor = white]
  deploy_binary [label = 'Deploy Binary CNN\\n(deploy_CNN_binary.R)', shape = rectangle, style = filled, fillcolor = orange]
  deploy_multi [label = 'Deploy Multi CNN\\n(deploy_CNN_multi.R)', shape = rectangle, style = filled, fillcolor = orange]

  data_viz [label = 'Extract embeddings + \n Unsupervised Clustering \n (Optional Step)', shape = diamond, style = filled, fillcolor = white]
  extract_embed [label = 'Extract Embeddings \\n(extract_embeddings.R)', shape = rectangle, style = filled, fillcolor = cyan]

  # Define Dependencies with Decision Points
  prepare_data -> spectrogram
  spectrogram -> train_model
  train_model -> { train_binary train_multi }

  { train_binary train_multi } -> eval_model
  eval_model -> best_performance
  best_performance -> eval_test_set
  eval_test_set -> { eval_binary eval_multi }
  { eval_binary eval_multi } -> deploy_model
  deploy_model -> { deploy_binary deploy_multi }

  { deploy_binary deploy_multi } -> data_viz
  data_viz -> extract_embed
}

"

DiagrammeR::grViz(flowchart)


```


