# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit gibbonNetR-MS-format.Rmd to modify this file

## ---- echo=FALSE, out.width="50%",fig.cap='Spectrograms of training clips for CNNs',fig.align='center',fig.pos='ht'----
knitr::include_graphics("/Users/denaclink/Desktop/RStudioProjects/gibbonNetR/README_files/spectro.png")


## ---- fig.align='left',fig.cap='Evaluating performance of pretrained CNNs', echo=FALSE, warning=FALSE, message=FALSE, fig.pos='h', results='hide', fig.width=6.5----
devtools::load_all("/Users/denaclink/Desktop/RStudioProjects/gibbonNetR")

performancetables.dir <- '/Users/denaclink/Desktop/RStudioProjects/gibbonNetR/data/_output_unfrozen_TRUE_imagesmalaysia_/performance_tables/'
PerformanceOutput <- gibbonNetR::get_best_performance(performancetables.dir=performancetables.dir)

PerformanceOutput$f1_plot

